# Generated by Django 4.1.2 on 2022-12-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capswebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='year',
            field=models.CharField(blank=True, choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year'), ('6th Year', '6th Year')], max_length=10, null=True, verbose_name='Year'),
        ),
    ]
